apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zx2uguoy4-go
  janus-idp.io/tekton: zx2uguoy4-go
  backstage.io/kubernetes-id: zx2uguoy4-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zx2uguoy4-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
